### ISSUE TITLE
the

### ISSUE THREAD

**Issue by TheThunderGuyS** [HurricanePootis/team-comtress-2#26]
### Checklist

- [ ] None of the open *or* closed issues document this problem.
- [ ] This is a bug, not a new idea.
- [ ] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch.

- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [ ] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1.
2.
3.

#### Client Settings

- *Server or client:* 
- *Operating system:* 
- *Team Comtress version:* 
- *Custom content:* 
- *Launch options:* 
#### Driver Version

- *Graphics driver:* 
- *DirectX level:* 
#### Hardware Specs

- *CPU model:* 
- *GPU model:* 
- *RAM amount:* 
- *TF2 install location:* 
- *TC2 install location:* 
- *TC2 installation method:* 
![image](https://user-images.githubusercontent.com/52540509/115277857-c0bc9600-a112-11eb-85b3-c5ea9e1b8dae.png)

![image](https://user-images.githubusercontent.com/52540509/115277864-c1552c80-a112-11eb-9322-812b71265998.png)

![image](https://user-images.githubusercontent.com/52540509/115277865-c1edc300-a112-11eb-874d-9f4a749ec667.png)

**Comment by micwoj92** [comment]
![image](https://user-images.githubusercontent.com/45581170/115279141-9c7aac80-a146-11eb-8dd0-8afd7edc111b.png)
